airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("flights/", include("flights.urls"))
]

flights/urls.py
from django.urls import path
from . import views

app_name = 'flights'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

flights/models.py
from pyexpat import model
from django.db import models

# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"


class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

    def is_valid_flight(self):
        return self.origin != self.destination and self.duration > 0


class Passenger(models.Model):
    first = models.CharField(max_length=10)
    last = models.CharField(max_length=10)
    flights = models.ManyToManyField(Flight, blank=True, related_name='passengers')

    def __str__(self) -> str:
        return f'{self.first} {self.last}'
    

flights/views.py
from django.shortcuts import render
from flights.models import Flight, Passenger
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    return render(request, "flights/index.html", {
        "flights": Flight.objects.all()
    })

def flight(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    return render(request, "flights/flight.html", {
        "flight": flight,
        "passengers": flight.passengers.all(),
        "non_passengers": Passenger.objects.exclude(flights=flight).all()
    })

def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk=flight_id)
        passenger_id = request.POST["passenger"]
        passenger = passenger.objects.get(pk=passenger_id)
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse("flights:flight", args=(flight.id,)))

flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flight {{ flight.id }}</h1>
    <ul>
        <li>Origin: {{ flight.origin }}</li>
        <li>Destination: {{ flight.destination }}</li>
        <li>Duration: {{ flight.duration }} minutes</li>
    </ul>
    <h2>Passengers</h2>
    <ul>
        {% for passenger in passengers %}
        <li>{{passenger.first}} {{passenger.last}}</li>
        {% empty %}
        <li>No Passengers</li>
        {% endfor %}
    </ul>
    <h3>Book a flight</h3>
    <form action="{% url 'flights:book' flight.id %}" method="post">
        {% csrf_token %}
        <select name="passenger">
            {% for passenger in non_passengers %}
            <option value="{{passenger.id}}">{{passenger}}</option>
            {% endfor %}
        </select>
        <input type="submit" />
    </form>
    <a href="{% url 'flights:index' %}">All Flights</a>
{% endblock %}

flights/templates/flights/index.html
{% extends  "flights/layout.html" %}

{% block body %}
<h1>Flights</h1>
<ul>
    {% for flight in flights %}
    <li><a href="{% url 'flights:flight' flight.id %}">Flight {{flight.id}}: {{ flight.origin }} to {{ flight.destination }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Flights</title>
  </head>
  <body>
    {% block body %} 
    {% endblock %}
  </body>
</html>